[custom]
clash_rule_base=https://raw.githubusercontent.com/lansepyy/opikuu/main/ikuuu-mi.yaml
enable_rule_generator=false
overwrite_original_rules=false

;===== 代理分组 =====
custom_proxy_group=🔰 选择节点`select`[]♻ 自动选择`(?i)香港|HK|🇭🇰`(?i)日本|JP|🇯🇵`(?i)台湾|TW|🇹🇼`(?i)新加坡|SG|🇸🇬`(?i)美国|US|🇺🇸`(?i)英国|GB|UK|🇬🇧`(?i)阿根廷|AR|🇦🇷`(?i)俄罗斯|RU|🇷🇺`(?i)土耳其|TR|🇹🇷`(?i)韩国|KR|🇰🇷`(?i)印度|IN|🇮🇳`(?i)德国|DE|🇩🇪`(?i)加拿大|CA|🇨🇦`(?i)澳大利亚|AU|🇦🇺`(?i)法国|FR|🇫🇷`(?i)乌克兰|UA|🇺🇦`.*`DIRECT
custom_proxy_group=♻ 自动选择`url-test`(?i)IEPL`http://cp.cloudflare.com`300,,50
custom_proxy_group=🌏 爱奇艺&哔哩哔哩`select`DIRECT`(?i)香港|HK|🇭🇰`(?i)台湾|TW|🇹🇼`[]🔰 选择节点
custom_proxy_group=📺 动画疯`select`[]🔰 选择节点`(?i)台湾|TW|🇹🇼`DIRECT
custom_proxy_group=🎮 Steam 登录/下载`select`DIRECT`[]🔰 选择节点`(?i)阿根廷|AR|🇦🇷`(?i)俄罗斯|RU|🇷🇺`(?i)土耳其|TR|🇹🇷`(?i)印度|IN|🇮🇳
custom_proxy_group=🎮 Steam 商店/社区`select`[]🔰 选择节点`(?i)阿根廷|AR|🇦🇷`(?i)俄罗斯|RU|🇷🇺`(?i)土耳其|TR|🇹🇷`(?i)印度|IN|🇮🇳`DIRECT
custom_proxy_group=🌩️ Cloudflare`select`[]🔰 选择节点`DIRECT
custom_proxy_group=☁️ OneDrive`select`[]🔰 选择节点`DIRECT`(?i)日本|JP|🇯🇵`(?i)香港|HK|🇭🇰
custom_proxy_group=🎓学术网站`select`DIRECT`[]🔰 选择节点
custom_proxy_group=🇨🇳 国内网站`select`DIRECT`[]🔰 选择节点
custom_proxy_group=🛑 拦截广告`select`REJECT`DIRECT`[]🔰 选择节点
custom_proxy_group=🐟 漏网之鱼`select`[]🔰 选择节点`DIRECT
