[custom]
clash_rule_base=https://raw.githubusercontent.com/lansepyy/opikuu/main/ikuuu-mi.yaml
enable_rule_generator=false
overwrite_original_rules=false

;===== 代理分组 =====
custom_proxy_group=🔀 选择节点`select`[]♻ 自动选择`[]🇭🇰 香港`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇹🇼 台湾`[]🇺🇸 美国`[]🇬🇧 英国`[]🇦🇷 阿根廷`[]🇷🇺 俄罗斯`[]🇹🇷 土耳其`[]🇰🇷 韩国`[]🇮🇳 印度`[]🇩🇪 德国`[]🇨🇦 加拿大`[]🇦🇺 澳大利亚`[]🇫🇷 法国`[]🇺🇦 乌克兰`[]免费`DIRECT

custom_proxy_group=♻ 自动选择`url-test`[]IEPL`http://cp.cloudflare.com`300,,50

custom_proxy_group=🌏 爱奇艺&哔哩哔哩`select`DIRECT`[]🇭🇰 香港`[]🇹🇼 台湾`[]🔀 选择节点

custom_proxy_group=📺 动画疯`select`[]🔀 选择节点`[]🇹🇼 台湾`DIRECT

custom_proxy_group=🎮 Steam 登录/下载`select`DIRECT`[]🔀 选择节点`[]🇦🇷 阿根廷`[]🇷🇺 俄罗斯`[]🇹🇷 土耳其`[]🇮🇳 印度

custom_proxy_group=🎮 Steam 商店/社区`select`[]🔀 选择节点`[]🇦🇷 阿根廷`[]🇷🇺 俄罗斯`[]🇹🇷 土耳其`[]🇮🇳 印度`DIRECT

custom_proxy_group=🌩️ Cloudflare`select`[]🔀 选择节点`DIRECT

custom_proxy_group=☁️ OneDrive`select`[]🔀 选择节点`DIRECT`[]🇯🇵 日本`[]🇭🇰 香港

custom_proxy_group=🎓学术网站`select`DIRECT`[]🔀 选择节点

custom_proxy_group=🇨🇳 国内网站`select`DIRECT`[]🔀 选择节点

custom_proxy_group=🛑 拦截广告`select`REJECT`DIRECT`[]🔀 选择节点

custom_proxy_group=🐟 漏网之鱼`select`[]🔀 选择节点`DIRECT
