[custom]
clash_rule_base=https://raw.githubusercontent.com/lansepyy/opikuu/main/ikuuu-mi.yaml
enable_rule_generator=false
overwrite_original_rules=false

;===== 代理分组 =====
custom_proxy_group=🔰 选择节点`select`♻ 自动选择`🇭🇰 香港Y01`🇯🇵 日本Y01 | IEPL`🇭🇰 香港Y02 | IEPL`🇯🇵 日本Y02 | IEPL`🇭🇰 香港Y03 | IEPL`🇯🇵 日本Y03 | IEPL`🇭🇰 香港Y04 | IEPL`🇯🇵 日本Y04 | IEPL`🇭🇰 香港Y05 | IEPL`🇯🇵 日本Y05 | 下载专用 | x0.01`🇭🇰 香港Y06 | x0.8`🇯🇵 日本Y06 | 下载专用 | x0.01`🇭🇰 香港Y07 | x0.8`🇯🇵 日本Y07 | IEPL`🇭🇰 香港Y08 | x0.8`🇯🇵 日本Y08 | IEPL`🇭🇰 香港Y09 | IEPL`🇯🇵 日本Y09 | IEPL`🇭🇰 香港Y10 | IEPL`🇯🇵 日本Y10 | IEPL`🇭🇰 香港Y11 | IEPL`🇯🇵 日本Y11 | IEPL`🇸🇬 新加坡Y01 | IEPL | x2`🇸🇬 新加坡Y02 | IEPL | x2`🇸🇬 新加坡Y03 | IEPL | x2`🇹🇼 台湾Y01 | IEPL | x2`🇺🇸 美国Y01 | IEPL | x1.5`🇺🇸 美国Y02 | IEPL | x1.5`🇬🇧 英国Y01`🇦🇷 阿根廷Y01`🇷🇺 俄罗斯Y01`🇹🇷 土耳其Y01`🇰🇷 韩国Y01`🇮🇳 印度Y01`🇩🇪 德国Y01`🇨🇦 加拿大Y01`🇦🇺 澳大利亚Y01`🇫🇷 法国Y01`🇺🇦 乌克兰Y01`🇯🇵 免费-日本1-Ver.7`🇯🇵 免费-日本2-Ver.8`🇯🇵 免费-日本3-Ver.7`🇯🇵 免费-日本4-Ver.8`🇯🇵 免费-日本5-Ver.9`🇯🇵 免费-日本6-Ver.8`🇯🇵 免费-日本7-Ver.2`DIRECT

custom_proxy_group=♻ 自动选择`url-test`🇭🇰 香港Y02 | IEPL`🇭🇰 香港Y03 | IEPL`🇭🇰 香港Y04 | IEPL`🇭🇰 香港Y05 | IEPL`🇭🇰 香港Y09 | IEPL`🇭🇰 香港Y10 | IEPL`🇭🇰 香港Y11 | IEPL`🇹🇼 台湾Y01 | IEPL | x2`🇯🇵 日本Y01 | IEPL`🇯🇵 日本Y02 | IEPL`🇯🇵 日本Y03 | IEPL`🇯🇵 日本Y04 | IEPL`🇯🇵 日本Y07 | IEPL`🇯🇵 日本Y08 | IEPL`🇯🇵 日本Y09 | IEPL`🇯🇵 日本Y10 | IEPL`🇯🇵 日本Y11 | IEPL`http://cp.cloudflare.com`300,,50

custom_proxy_group=🌏 爱奇艺&哔哩哔哩`select`DIRECT`🇭🇰 香港Y01`🇭🇰 香港Y02 | IEPL`🇭🇰 香港Y03 | IEPL`🇭🇰 香港Y04 | IEPL`🇭🇰 香港Y05 | IEPL`🇭🇰 香港Y06 | x0.8`🇭🇰 香港Y07 | x0.8`🇭🇰 香港Y08 | x0.8`🇭🇰 香港Y09 | IEPL`🇭🇰 香港Y10 | IEPL`🇭🇰 香港Y11 | IEPL`🇹🇼 台湾Y01 | IEPL | x2`🔰 选择节点

custom_proxy_group=📺 动画疯`select`🔰 选择节点`🇹🇼 台湾Y01 | IEPL | x2`DIRECT

custom_proxy_group=🎮 Steam 登录/下载`select`DIRECT`🔰 选择节点`🇦🇷 阿根廷Y01`🇷🇺 俄罗斯Y01`🇹🇷 土耳其Y01`🇮🇳 印度Y01

custom_proxy_group=🎮 Steam 商店/社区`select`🔰 选择节点`🇦🇷 阿根廷Y01`🇷🇺 俄罗斯Y01`🇹🇷 土耳其Y01`🇮🇳 印度Y01`DIRECT

custom_proxy_group=🌩️ Cloudflare`select`🔰 选择节点`DIRECT

custom_proxy_group=☁️ OneDrive`select`🔰 选择节点`DIRECT`🇯🇵 日本Y01 | IEPL`🇯🇵 日本Y02 | IEPL`🇯🇵 日本Y03 | IEPL`🇯🇵 日本Y04 | IEPL`🇯🇵 日本Y05 | 下载专用 | x0.01`🇯🇵 日本Y06 | 下载专用 | x0.01`🇯🇵 日本Y07 | IEPL`🇯🇵 日本Y08 | IEPL`🇯🇵 日本Y09 | IEPL`🇯🇵 日本Y10 | IEPL`🇯🇵 日本Y11 | IEPL`🇯🇵 免费-日本1-Ver.7`🇯🇵 免费-日本2-Ver.8`🇯🇵 免费-日本3-Ver.7`🇯🇵 免费-日本4-Ver.8`🇯🇵 免费-日本5-Ver.9`🇯🇵 免费-日本6-Ver.8`🇯🇵 免费-日本7-Ver.2`🇭🇰 香港Y01`🇭🇰 香港Y02 | IEPL`🇭🇰 香港Y03 | IEPL`🇭🇰 香港Y04 | IEPL`🇭🇰 香港Y05 | IEPL`🇭🇰 香港Y06 | x0.8`🇭🇰 香港Y07 | x0.8`🇭🇰 香港Y08 | x0.8`🇭🇰 香港Y09 | IEPL`🇭🇰 香港Y10 | IEPL`🇭🇰 香港Y11 | IEPL

custom_proxy_group=🎓学术网站`select`DIRECT`🔰 选择节点

custom_proxy_group=🇨🇳 国内网站`select`DIRECT`🔰 选择节点

custom_proxy_group=🛑 拦截广告`select`REJECT`DIRECT`🔰 选择节点

custom_proxy_group=🐟 漏网之鱼`select`🔰 选择节点`DIRECT
